#############################################################################
# Makefile for building: Library_Database.app/Contents/MacOS/Library_Database
# Generated by qmake (3.1) (Qt 5.8.0)
# Project:  ../Library_Database/Library_Database.pro
# Template: app
# Command: /Users/apple/Qt/5.8/clang_64/bin/qmake -o Makefile ../Library_Database/Library_Database.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_CFLAGS) -g -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_CFLAGS) -g -std=gnu++11 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I../Library_Database -I. -I../../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers -I../../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers -I../../../../Qt/5.8/clang_64/lib/QtSql.framework/Headers -I../../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../../../../Qt/5.8/clang_64/mkspecs/macx-clang -F/Users/apple/Qt/5.8/clang_64/lib
QMAKE         = /Users/apple/Qt/5.8/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Library_Database1.0.0
DISTDIR = /Users/apple/Documents/?????/????/build-Library_Database-Desktop_Qt_5_8_0_clang_64bit-Debug/.tmp/Library_Database1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_LFLAGS) -Wl,-rpath,/Users/apple/Qt/5.8/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/apple/Qt/5.8/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework QtSql -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../Library_Database/main.cpp \
		../Library_Database/mainwindow.cpp \
		../Library_Database/dialog.cpp \
		../Library_Database/searchcard.cpp \
		../Library_Database/returnbook.cpp \
		../Library_Database/borrowbook.cpp \
		../Library_Database/addbook.cpp \
		../Library_Database/managecard.cpp moc_mainwindow.cpp \
		moc_dialog.cpp \
		moc_searchcard.cpp \
		moc_returnbook.cpp \
		moc_borrowbook.cpp \
		moc_addbook.cpp \
		moc_managecard.cpp
OBJECTS       = main.o \
		mainwindow.o \
		dialog.o \
		searchcard.o \
		returnbook.o \
		borrowbook.o \
		addbook.o \
		managecard.o \
		moc_mainwindow.o \
		moc_dialog.o \
		moc_searchcard.o \
		moc_returnbook.o \
		moc_borrowbook.o \
		moc_addbook.o \
		moc_managecard.o
DIST          = ../../../../Qt/5.8/clang_64/mkspecs/features/spec_pre.prf \
		../../../../Qt/5.8/clang_64/mkspecs/qdevice.pri \
		../../../../Qt/5.8/clang_64/mkspecs/features/device_config.prf \
		../../../../Qt/5.8/clang_64/mkspecs/common/unix.conf \
		../../../../Qt/5.8/clang_64/mkspecs/common/mac.conf \
		../../../../Qt/5.8/clang_64/mkspecs/common/macx.conf \
		../../../../Qt/5.8/clang_64/mkspecs/common/sanitize.conf \
		../../../../Qt/5.8/clang_64/mkspecs/common/gcc-base.conf \
		../../../../Qt/5.8/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../Qt/5.8/clang_64/mkspecs/common/clang.conf \
		../../../../Qt/5.8/clang_64/mkspecs/common/clang-mac.conf \
		../../../../Qt/5.8/clang_64/mkspecs/qconfig.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/features/qt_functions.prf \
		../../../../Qt/5.8/clang_64/mkspecs/features/qt_config.prf \
		../../../../Qt/5.8/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../../Qt/5.8/clang_64/mkspecs/features/spec_post.prf \
		../../../../Qt/5.8/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../Qt/5.8/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../Qt/5.8/clang_64/mkspecs/features/toolchain.prf \
		../../../../Qt/5.8/clang_64/mkspecs/features/mac/toolchain.prf \
		../../../../Qt/5.8/clang_64/mkspecs/features/default_pre.prf \
		../../../../Qt/5.8/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../../Qt/5.8/clang_64/mkspecs/features/resolve_config.prf \
		../../../../Qt/5.8/clang_64/mkspecs/features/default_post.prf \
		../../../../Qt/5.8/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../Qt/5.8/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../Qt/5.8/clang_64/mkspecs/features/qml_debug.prf \
		../../../../Qt/5.8/clang_64/mkspecs/features/warn_on.prf \
		../../../../Qt/5.8/clang_64/mkspecs/features/qt.prf \
		../../../../Qt/5.8/clang_64/mkspecs/features/resources.prf \
		../../../../Qt/5.8/clang_64/mkspecs/features/moc.prf \
		../../../../Qt/5.8/clang_64/mkspecs/features/unix/opengl.prf \
		../../../../Qt/5.8/clang_64/mkspecs/features/uic.prf \
		../../../../Qt/5.8/clang_64/mkspecs/features/unix/thread.prf \
		../../../../Qt/5.8/clang_64/mkspecs/features/qmake_use.prf \
		../../../../Qt/5.8/clang_64/mkspecs/features/file_copies.prf \
		../../../../Qt/5.8/clang_64/mkspecs/features/mac/rez.prf \
		../../../../Qt/5.8/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../../Qt/5.8/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../Qt/5.8/clang_64/mkspecs/features/exceptions.prf \
		../../../../Qt/5.8/clang_64/mkspecs/features/yacc.prf \
		../../../../Qt/5.8/clang_64/mkspecs/features/lex.prf \
		../Library_Database/Library_Database.pro ../Library_Database/mainwindow.h \
		../Library_Database/dialog.h \
		../Library_Database/searchcard.h \
		../Library_Database/returnbook.h \
		../Library_Database/borrowbook.h \
		../Library_Database/addbook.h \
		../Library_Database/managecard.h ../Library_Database/main.cpp \
		../Library_Database/mainwindow.cpp \
		../Library_Database/dialog.cpp \
		../Library_Database/searchcard.cpp \
		../Library_Database/returnbook.cpp \
		../Library_Database/borrowbook.cpp \
		../Library_Database/addbook.cpp \
		../Library_Database/managecard.cpp
QMAKE_TARGET  = Library_Database
DESTDIR       = 
TARGET        = Library_Database.app/Contents/MacOS/Library_Database


first: all
####### Build rules

$(TARGET): ui_mainwindow.h ui_dialog.h ui_searchcard.h ui_returnbook.h ui_borrowbook.h ui_addbook.h ui_managecard.h $(OBJECTS)  
	@test -d Library_Database.app/Contents/MacOS/ || mkdir -p Library_Database.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ../Library_Database/Library_Database.pro ../../../../Qt/5.8/clang_64/mkspecs/macx-clang/qmake.conf ../../../../Qt/5.8/clang_64/mkspecs/features/spec_pre.prf \
		../../../../Qt/5.8/clang_64/mkspecs/qdevice.pri \
		../../../../Qt/5.8/clang_64/mkspecs/features/device_config.prf \
		../../../../Qt/5.8/clang_64/mkspecs/common/unix.conf \
		../../../../Qt/5.8/clang_64/mkspecs/common/mac.conf \
		../../../../Qt/5.8/clang_64/mkspecs/common/macx.conf \
		../../../../Qt/5.8/clang_64/mkspecs/common/sanitize.conf \
		../../../../Qt/5.8/clang_64/mkspecs/common/gcc-base.conf \
		../../../../Qt/5.8/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../Qt/5.8/clang_64/mkspecs/common/clang.conf \
		../../../../Qt/5.8/clang_64/mkspecs/common/clang-mac.conf \
		../../../../Qt/5.8/clang_64/mkspecs/qconfig.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt/5.8/clang_64/mkspecs/features/qt_functions.prf \
		../../../../Qt/5.8/clang_64/mkspecs/features/qt_config.prf \
		../../../../Qt/5.8/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../../Qt/5.8/clang_64/mkspecs/features/spec_post.prf \
		../../../../Qt/5.8/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../Qt/5.8/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../Qt/5.8/clang_64/mkspecs/features/toolchain.prf \
		../../../../Qt/5.8/clang_64/mkspecs/features/mac/toolchain.prf \
		../../../../Qt/5.8/clang_64/mkspecs/features/default_pre.prf \
		../../../../Qt/5.8/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../../Qt/5.8/clang_64/mkspecs/features/resolve_config.prf \
		../../../../Qt/5.8/clang_64/mkspecs/features/default_post.prf \
		../../../../Qt/5.8/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../Qt/5.8/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../Qt/5.8/clang_64/mkspecs/features/qml_debug.prf \
		../../../../Qt/5.8/clang_64/mkspecs/features/warn_on.prf \
		../../../../Qt/5.8/clang_64/mkspecs/features/qt.prf \
		../../../../Qt/5.8/clang_64/mkspecs/features/resources.prf \
		../../../../Qt/5.8/clang_64/mkspecs/features/moc.prf \
		../../../../Qt/5.8/clang_64/mkspecs/features/unix/opengl.prf \
		../../../../Qt/5.8/clang_64/mkspecs/features/uic.prf \
		../../../../Qt/5.8/clang_64/mkspecs/features/unix/thread.prf \
		../../../../Qt/5.8/clang_64/mkspecs/features/qmake_use.prf \
		../../../../Qt/5.8/clang_64/mkspecs/features/file_copies.prf \
		../../../../Qt/5.8/clang_64/mkspecs/features/mac/rez.prf \
		../../../../Qt/5.8/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../../Qt/5.8/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../Qt/5.8/clang_64/mkspecs/features/exceptions.prf \
		../../../../Qt/5.8/clang_64/mkspecs/features/yacc.prf \
		../../../../Qt/5.8/clang_64/mkspecs/features/lex.prf \
		../Library_Database/Library_Database.pro \
		../../../../Qt/5.8/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		../../../../Qt/5.8/clang_64/lib/QtGui.framework/QtGui.prl \
		../../../../Qt/5.8/clang_64/lib/QtSql.framework/QtSql.prl \
		../../../../Qt/5.8/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile ../Library_Database/Library_Database.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
../../../../Qt/5.8/clang_64/mkspecs/features/spec_pre.prf:
../../../../Qt/5.8/clang_64/mkspecs/qdevice.pri:
../../../../Qt/5.8/clang_64/mkspecs/features/device_config.prf:
../../../../Qt/5.8/clang_64/mkspecs/common/unix.conf:
../../../../Qt/5.8/clang_64/mkspecs/common/mac.conf:
../../../../Qt/5.8/clang_64/mkspecs/common/macx.conf:
../../../../Qt/5.8/clang_64/mkspecs/common/sanitize.conf:
../../../../Qt/5.8/clang_64/mkspecs/common/gcc-base.conf:
../../../../Qt/5.8/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../../Qt/5.8/clang_64/mkspecs/common/clang.conf:
../../../../Qt/5.8/clang_64/mkspecs/common/clang-mac.conf:
../../../../Qt/5.8/clang_64/mkspecs/qconfig.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_charts.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_networkauth.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../../Qt/5.8/clang_64/mkspecs/features/qt_functions.prf:
../../../../Qt/5.8/clang_64/mkspecs/features/qt_config.prf:
../../../../Qt/5.8/clang_64/mkspecs/macx-clang/qmake.conf:
../../../../Qt/5.8/clang_64/mkspecs/features/spec_post.prf:
../../../../Qt/5.8/clang_64/mkspecs/features/exclusive_builds.prf:
../../../../Qt/5.8/clang_64/mkspecs/features/mac/sdk.prf:
../../../../Qt/5.8/clang_64/mkspecs/features/toolchain.prf:
../../../../Qt/5.8/clang_64/mkspecs/features/mac/toolchain.prf:
../../../../Qt/5.8/clang_64/mkspecs/features/default_pre.prf:
../../../../Qt/5.8/clang_64/mkspecs/features/mac/default_pre.prf:
../../../../Qt/5.8/clang_64/mkspecs/features/resolve_config.prf:
../../../../Qt/5.8/clang_64/mkspecs/features/default_post.prf:
../../../../Qt/5.8/clang_64/mkspecs/features/mac/default_post.prf:
../../../../Qt/5.8/clang_64/mkspecs/features/mac/objective_c.prf:
../../../../Qt/5.8/clang_64/mkspecs/features/qml_debug.prf:
../../../../Qt/5.8/clang_64/mkspecs/features/warn_on.prf:
../../../../Qt/5.8/clang_64/mkspecs/features/qt.prf:
../../../../Qt/5.8/clang_64/mkspecs/features/resources.prf:
../../../../Qt/5.8/clang_64/mkspecs/features/moc.prf:
../../../../Qt/5.8/clang_64/mkspecs/features/unix/opengl.prf:
../../../../Qt/5.8/clang_64/mkspecs/features/uic.prf:
../../../../Qt/5.8/clang_64/mkspecs/features/unix/thread.prf:
../../../../Qt/5.8/clang_64/mkspecs/features/qmake_use.prf:
../../../../Qt/5.8/clang_64/mkspecs/features/file_copies.prf:
../../../../Qt/5.8/clang_64/mkspecs/features/mac/rez.prf:
../../../../Qt/5.8/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../../../../Qt/5.8/clang_64/mkspecs/features/testcase_targets.prf:
../../../../Qt/5.8/clang_64/mkspecs/features/exceptions.prf:
../../../../Qt/5.8/clang_64/mkspecs/features/yacc.prf:
../../../../Qt/5.8/clang_64/mkspecs/features/lex.prf:
../Library_Database/Library_Database.pro:
../../../../Qt/5.8/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
../../../../Qt/5.8/clang_64/lib/QtGui.framework/QtGui.prl:
../../../../Qt/5.8/clang_64/lib/QtSql.framework/QtSql.prl:
../../../../Qt/5.8/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile ../Library_Database/Library_Database.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

qmake_all: FORCE

Library_Database.app/Contents/PkgInfo: 
	@test -d Library_Database.app/Contents || mkdir -p Library_Database.app/Contents
	@$(DEL_FILE) Library_Database.app/Contents/PkgInfo
	@echo "APPL????" > Library_Database.app/Contents/PkgInfo
Library_Database.app/Contents/Resources/empty.lproj: 
	@test -d Library_Database.app/Contents/Resources || mkdir -p Library_Database.app/Contents/Resources
	@touch Library_Database.app/Contents/Resources/empty.lproj
	
Library_Database.app/Contents/Info.plist: 
	@test -d Library_Database.app/Contents || mkdir -p Library_Database.app/Contents
	@$(DEL_FILE) Library_Database.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,Review.Library-Database,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,Library_Database,g" -e "s,@LIBRARY@,Library_Database,g" -e "s,@TYPEINFO@,????,g" ../../../../Qt/5.8/clang_64/mkspecs/macx-clang/Info.plist.app >Library_Database.app/Contents/Info.plist

all: Makefile \
		Library_Database.app/Contents/PkgInfo \
		Library_Database.app/Contents/Resources/empty.lproj \
		Library_Database.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../../../Qt/5.8/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ../Library_Database/mainwindow.h ../Library_Database/dialog.h ../Library_Database/searchcard.h ../Library_Database/returnbook.h ../Library_Database/borrowbook.h ../Library_Database/addbook.h ../Library_Database/managecard.h $(DISTDIR)/
	$(COPY_FILE) --parents ../Library_Database/main.cpp ../Library_Database/mainwindow.cpp ../Library_Database/dialog.cpp ../Library_Database/searchcard.cpp ../Library_Database/returnbook.cpp ../Library_Database/borrowbook.cpp ../Library_Database/addbook.cpp ../Library_Database/managecard.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ../Library_Database/mainwindow.ui ../Library_Database/dialog.ui ../Library_Database/searchcard.ui ../Library_Database/returnbook.ui ../Library_Database/borrowbook.ui ../Library_Database/addbook.ui ../Library_Database/managecard.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r Library_Database.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../../../Qt/5.8/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_CFLAGS) -g -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h ../../../../Qt/5.8/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_dialog.cpp moc_searchcard.cpp moc_returnbook.cpp moc_borrowbook.cpp moc_addbook.cpp moc_managecard.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_dialog.cpp moc_searchcard.cpp moc_returnbook.cpp moc_borrowbook.cpp moc_addbook.cpp moc_managecard.cpp
moc_mainwindow.cpp: ../../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../Library_Database/mainwindow.h \
		moc_predefs.h \
		../../../../Qt/5.8/clang_64/bin/moc
	/Users/apple/Qt/5.8/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/apple/Qt/5.8/clang_64/mkspecs/macx-clang -I/Users/apple/Documents/?????/????/Library_Database -I/Users/apple/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers -I/Users/apple/Qt/5.8/clang_64/lib/QtGui.framework/Headers -I/Users/apple/Qt/5.8/clang_64/lib/QtSql.framework/Headers -I/Users/apple/Qt/5.8/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/Users/apple/Qt/5.8/clang_64/lib ../Library_Database/mainwindow.h -o moc_mainwindow.cpp

moc_dialog.cpp: ../../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../Library_Database/dialog.h \
		moc_predefs.h \
		../../../../Qt/5.8/clang_64/bin/moc
	/Users/apple/Qt/5.8/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/apple/Qt/5.8/clang_64/mkspecs/macx-clang -I/Users/apple/Documents/?????/????/Library_Database -I/Users/apple/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers -I/Users/apple/Qt/5.8/clang_64/lib/QtGui.framework/Headers -I/Users/apple/Qt/5.8/clang_64/lib/QtSql.framework/Headers -I/Users/apple/Qt/5.8/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/Users/apple/Qt/5.8/clang_64/lib ../Library_Database/dialog.h -o moc_dialog.cpp

moc_searchcard.cpp: ../../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../Library_Database/searchcard.h \
		moc_predefs.h \
		../../../../Qt/5.8/clang_64/bin/moc
	/Users/apple/Qt/5.8/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/apple/Qt/5.8/clang_64/mkspecs/macx-clang -I/Users/apple/Documents/?????/????/Library_Database -I/Users/apple/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers -I/Users/apple/Qt/5.8/clang_64/lib/QtGui.framework/Headers -I/Users/apple/Qt/5.8/clang_64/lib/QtSql.framework/Headers -I/Users/apple/Qt/5.8/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/Users/apple/Qt/5.8/clang_64/lib ../Library_Database/searchcard.h -o moc_searchcard.cpp

moc_returnbook.cpp: ../../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../Library_Database/returnbook.h \
		moc_predefs.h \
		../../../../Qt/5.8/clang_64/bin/moc
	/Users/apple/Qt/5.8/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/apple/Qt/5.8/clang_64/mkspecs/macx-clang -I/Users/apple/Documents/?????/????/Library_Database -I/Users/apple/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers -I/Users/apple/Qt/5.8/clang_64/lib/QtGui.framework/Headers -I/Users/apple/Qt/5.8/clang_64/lib/QtSql.framework/Headers -I/Users/apple/Qt/5.8/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/Users/apple/Qt/5.8/clang_64/lib ../Library_Database/returnbook.h -o moc_returnbook.cpp

moc_borrowbook.cpp: ../../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../Library_Database/borrowbook.h \
		moc_predefs.h \
		../../../../Qt/5.8/clang_64/bin/moc
	/Users/apple/Qt/5.8/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/apple/Qt/5.8/clang_64/mkspecs/macx-clang -I/Users/apple/Documents/?????/????/Library_Database -I/Users/apple/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers -I/Users/apple/Qt/5.8/clang_64/lib/QtGui.framework/Headers -I/Users/apple/Qt/5.8/clang_64/lib/QtSql.framework/Headers -I/Users/apple/Qt/5.8/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/Users/apple/Qt/5.8/clang_64/lib ../Library_Database/borrowbook.h -o moc_borrowbook.cpp

moc_addbook.cpp: ../../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../Library_Database/addbook.h \
		moc_predefs.h \
		../../../../Qt/5.8/clang_64/bin/moc
	/Users/apple/Qt/5.8/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/apple/Qt/5.8/clang_64/mkspecs/macx-clang -I/Users/apple/Documents/?????/????/Library_Database -I/Users/apple/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers -I/Users/apple/Qt/5.8/clang_64/lib/QtGui.framework/Headers -I/Users/apple/Qt/5.8/clang_64/lib/QtSql.framework/Headers -I/Users/apple/Qt/5.8/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/Users/apple/Qt/5.8/clang_64/lib ../Library_Database/addbook.h -o moc_addbook.cpp

moc_managecard.cpp: ../../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../Library_Database/managecard.h \
		moc_predefs.h \
		../../../../Qt/5.8/clang_64/bin/moc
	/Users/apple/Qt/5.8/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/apple/Qt/5.8/clang_64/mkspecs/macx-clang -I/Users/apple/Documents/?????/????/Library_Database -I/Users/apple/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers -I/Users/apple/Qt/5.8/clang_64/lib/QtGui.framework/Headers -I/Users/apple/Qt/5.8/clang_64/lib/QtSql.framework/Headers -I/Users/apple/Qt/5.8/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/Users/apple/Qt/5.8/clang_64/lib ../Library_Database/managecard.h -o moc_managecard.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_dialog.h ui_searchcard.h ui_returnbook.h ui_borrowbook.h ui_addbook.h ui_managecard.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_dialog.h ui_searchcard.h ui_returnbook.h ui_borrowbook.h ui_addbook.h ui_managecard.h
ui_mainwindow.h: ../Library_Database/mainwindow.ui \
		../../../../Qt/5.8/clang_64/bin/uic
	/Users/apple/Qt/5.8/clang_64/bin/uic ../Library_Database/mainwindow.ui -o ui_mainwindow.h

ui_dialog.h: ../Library_Database/dialog.ui \
		../../../../Qt/5.8/clang_64/bin/uic
	/Users/apple/Qt/5.8/clang_64/bin/uic ../Library_Database/dialog.ui -o ui_dialog.h

ui_searchcard.h: ../Library_Database/searchcard.ui \
		../../../../Qt/5.8/clang_64/bin/uic
	/Users/apple/Qt/5.8/clang_64/bin/uic ../Library_Database/searchcard.ui -o ui_searchcard.h

ui_returnbook.h: ../Library_Database/returnbook.ui \
		../../../../Qt/5.8/clang_64/bin/uic
	/Users/apple/Qt/5.8/clang_64/bin/uic ../Library_Database/returnbook.ui -o ui_returnbook.h

ui_borrowbook.h: ../Library_Database/borrowbook.ui \
		../../../../Qt/5.8/clang_64/bin/uic
	/Users/apple/Qt/5.8/clang_64/bin/uic ../Library_Database/borrowbook.ui -o ui_borrowbook.h

ui_addbook.h: ../Library_Database/addbook.ui \
		../../../../Qt/5.8/clang_64/bin/uic
	/Users/apple/Qt/5.8/clang_64/bin/uic ../Library_Database/addbook.ui -o ui_addbook.h

ui_managecard.h: ../Library_Database/managecard.ui \
		../../../../Qt/5.8/clang_64/bin/uic
	/Users/apple/Qt/5.8/clang_64/bin/uic ../Library_Database/managecard.ui -o ui_managecard.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: ../Library_Database/main.cpp ../Library_Database/mainwindow.h \
		../../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../../../Qt/5.8/clang_64/lib/QtSql.framework/Headers/QSqlDatabase \
		../../../../Qt/5.8/clang_64/lib/QtSql.framework/Headers/qsqldatabase.h \
		../../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../Library_Database/main.cpp

mainwindow.o: ../Library_Database/mainwindow.cpp ../Library_Database/mainwindow.h \
		../../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		ui_mainwindow.h \
		../Library_Database/dialog.h \
		../../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../Library_Database/searchcard.h \
		../Library_Database/returnbook.h \
		../Library_Database/borrowbook.h \
		../Library_Database/addbook.h \
		../Library_Database/managecard.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o ../Library_Database/mainwindow.cpp

dialog.o: ../Library_Database/dialog.cpp ../Library_Database/dialog.h \
		../../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		ui_dialog.h \
		../../../../Qt/5.8/clang_64/lib/QtSql.framework/Headers/QSqlQueryModel \
		../../../../Qt/5.8/clang_64/lib/QtSql.framework/Headers/qsqlquerymodel.h \
		../../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QTableView \
		../../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qtableview.h \
		../../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QString \
		../../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../../Qt/5.8/clang_64/lib/QtSql.framework/Headers/QSqlDatabase \
		../../../../Qt/5.8/clang_64/lib/QtSql.framework/Headers/qsqldatabase.h \
		../../../../Qt/5.8/clang_64/lib/QtSql.framework/Headers/QSqlQuery \
		../../../../Qt/5.8/clang_64/lib/QtSql.framework/Headers/qsqlquery.h \
		../../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialog.o ../Library_Database/dialog.cpp

searchcard.o: ../Library_Database/searchcard.cpp ../Library_Database/searchcard.h \
		../../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		ui_searchcard.h \
		../../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QString \
		../../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../../Qt/5.8/clang_64/lib/QtSql.framework/Headers/QSqlQuery \
		../../../../Qt/5.8/clang_64/lib/QtSql.framework/Headers/qsqlquery.h \
		../../../../Qt/5.8/clang_64/lib/QtSql.framework/Headers/QSqlQueryModel \
		../../../../Qt/5.8/clang_64/lib/QtSql.framework/Headers/qsqlquerymodel.h \
		../../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o searchcard.o ../Library_Database/searchcard.cpp

returnbook.o: ../Library_Database/returnbook.cpp ../Library_Database/returnbook.h \
		../../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		ui_returnbook.h \
		../../../../Qt/5.8/clang_64/lib/QtSql.framework/Headers/QSqlQuery \
		../../../../Qt/5.8/clang_64/lib/QtSql.framework/Headers/qsqlquery.h \
		../../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QDate \
		../../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qdatetime.h \
		../../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o returnbook.o ../Library_Database/returnbook.cpp

borrowbook.o: ../Library_Database/borrowbook.cpp ../Library_Database/borrowbook.h \
		../../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		ui_borrowbook.h \
		../../../../Qt/5.8/clang_64/lib/QtSql.framework/Headers/QSqlQuery \
		../../../../Qt/5.8/clang_64/lib/QtSql.framework/Headers/qsqlquery.h \
		../../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QString \
		../../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QDate \
		../../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qdatetime.h \
		../../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o borrowbook.o ../Library_Database/borrowbook.cpp

addbook.o: ../Library_Database/addbook.cpp ../Library_Database/addbook.h \
		../../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		ui_addbook.h \
		../../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QString \
		../../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../../Qt/5.8/clang_64/lib/QtSql.framework/Headers/QSqlQuery \
		../../../../Qt/5.8/clang_64/lib/QtSql.framework/Headers/qsqlquery.h \
		../../../../Qt/5.8/clang_64/lib/QtSql.framework/Headers/QSqlQueryModel \
		../../../../Qt/5.8/clang_64/lib/QtSql.framework/Headers/qsqlquerymodel.h \
		../../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o addbook.o ../Library_Database/addbook.cpp

managecard.o: ../Library_Database/managecard.cpp ../Library_Database/managecard.h \
		../../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		ui_managecard.h \
		../../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QString \
		../../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../../Qt/5.8/clang_64/lib/QtSql.framework/Headers/QSqlQuery \
		../../../../Qt/5.8/clang_64/lib/QtSql.framework/Headers/qsqlquery.h \
		../../../../Qt/5.8/clang_64/lib/QtSql.framework/Headers/QSqlQueryModel \
		../../../../Qt/5.8/clang_64/lib/QtSql.framework/Headers/qsqlquerymodel.h \
		../../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o managecard.o ../Library_Database/managecard.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_dialog.o: moc_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialog.o moc_dialog.cpp

moc_searchcard.o: moc_searchcard.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_searchcard.o moc_searchcard.cpp

moc_returnbook.o: moc_returnbook.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_returnbook.o moc_returnbook.cpp

moc_borrowbook.o: moc_borrowbook.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_borrowbook.o moc_borrowbook.cpp

moc_addbook.o: moc_addbook.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_addbook.o moc_addbook.cpp

moc_managecard.o: moc_managecard.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_managecard.o moc_managecard.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

